# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gaKiQzZiLX-sWJ5ISGDWtjcCn70CMI8b
"""

num_list=[1,2,3,4,66,7,8,9,0,5]
target=15

sum_list=[]
for i in num_list:
  for k in num_list:
    if i+k==target:
      sum_list.append(i)

print(sum_list)

list1=[1,2,3,4,5,6,7,8]
list2=[10,20,30,40,50,1,2,3,4]
list3=[]
for i in list1:
  for k in list2:
    if i==k:
      list3.append(k)
print(list3)

my_list=["yassin","ammar","yassin","hour","khadega"]
ypur_list=[]
ypur_list.append(my_list[::-1])
print(ypur_list)

